# Generated by Django 5.0.1 on 2025-05-15 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="Nível hierárquico (1=baixo, 10=alto)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "required_approvers",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Número de aprovadores necessários"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("equipment", "Equipamento"),
                            ("human", "Humano"),
                            ("service", "Serviço"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Localização onde a tarefa será executada",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("foundation", "Fundação"),
                    ("structure", "Estrutura"),
                    ("plumbing", "Encanamento"),
                    ("electrical", "Elétrico"),
                    ("painting", "Pintura"),
                    ("flooring", "Piso"),
                    ("finishing", "Acabamento"),
                    ("other", "Outro"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approval_authorities",
                        to="core.process",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_authorities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_users",
                        to="core.approvallevel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Approval Authorities",
                "unique_together": {("user", "level")},
            },
        ),
        migrations.CreateModel(
            name="ProcessResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_allocated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.process",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_allocations",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "unique_together": {("process", "resource")},
            },
        ),
        migrations.CreateModel(
            name="TaskResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_allocated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_allocations",
                        to="core.resource",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "resource")},
            },
        ),
    ]
